name: Compile Pawn

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make

    - name: Download Pawn compiler source
      run: |
        git clone https://github.com/compuphase/pawn.git

    - name: Build pawn compiler
      run: |
        cd pawn/source/compiler
        make

    - name: Copy compiler
      run: |
        sudo cp pawn/source/compiler/pawncc /usr/local/bin/

    - name: Compile gamemode
      run: |
        pawncc gamemodes/Main.pwn -o gamemodes/Main.amx

    - name: Upload AMX
      uses: actions/upload-artifact@v4
      with:
        name: gamemode
        path: gamemodes/Main.amx
