name: Compile Pawn

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Pawn compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y pawncc || true

    - name: Check compiler
      run: |
        which pawncc || echo "pawncc not found"

    - name: Compile gamemode
      run: |
        pawncc gamemodes/Main.pwn -o gamemodes/Main.amx

    - name: Upload AMX
      uses: actions/upload-artifact@v4
      with:
        name: gamemode
        path: gamemodes/Main.amx
